language: go

go:
  - 1.12

env:
  - GO111MODULE=on

script:
  - make test image

notifications:
  email: false

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: make deploy
  on:
    branch: master
