apis:
  test:
    name: "Testing"
    prefix: "test"
    upstream_url: "http://localhost:8080/invalid/url"
    methods: ["GET", "POST"]
    allow_cross_origin: true
    middlewares:
      logging: true

  typicode:
    name: "JSONPlaceholder"
    prefix: "typicode"
    upstream_url: "https://jsonplaceholder.typicode.com"
    middlewares:
      logging: true
