version: "3.5"

services:
  api-gateway:
    image: jaceys/viaduct:latest
    container_name: service.api-gateway
    volumes:
      - ./config.yml:/config/config.yml
    ports:
      - 5000:80

  service.backend-1:
    image: williamyeh/json-server:latest
    container_name: service.backend-1
    volumes:
      - ./users.json:/data/db.json
    command: --watch db.json

  service.backend-2:
    image: williamyeh/json-server:latest
    container_name: service.backend-2
    volumes:
      - ./todos.json:/data/db.json
    command: --watch db.json
